version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8080:8080"
    environment:
      - SLACK_TOKEN=${SLACK_TOKEN}
      - SLACK_CHANNEL=${SLACK_CHANNEL}
    volumes:
      - api_data:/app/data
    networks:
      - apollo_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

  operator-1:
    build:
      context: .
      dockerfile: Dockerfile.operator
    ports:
      - "8081:8081"
    environment:
      - OPERATOR_ID=operator-1
      - ENABLED_MODULES=mysql,kubernetes
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - KUBERNETES_CONFIG=/app/config/kubeconfig
    volumes:
      - operator_1_data:/app/data
      - ${KUBECONFIG_PATH}:/app/config/kubeconfig:ro
    networks:
      - apollo_network
    depends_on:
      api:
        condition: service_healthy

  operator-2:
    build:
      context: .
      dockerfile: Dockerfile.operator
    ports:
      - "8082:8081"
    environment:
      - OPERATOR_ID=operator-2
      - ENABLED_MODULES=mysql
      - MYSQL_HOST=${MYSQL_HOST_2}
      - MYSQL_PORT=${MYSQL_PORT_2}
      - MYSQL_USER=${MYSQL_USER_2}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD_2}
    volumes:
      - operator_2_data:/app/data
    networks:
      - apollo_network
    depends_on:
      api:
        condition: service_healthy

  cli:
    build:
      context: .
      dockerfile: Dockerfile.cli
    volumes:
      - ${HOME}/.apollo-cli:/app/config
    environment:
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    networks:
      - apollo_network
    depends_on:
      api:
        condition: service_healthy

networks:
  apollo_network:
    driver: bridge

volumes:
  api_data:
  operator_1_data:
  operator_2_data: 