server:
  port: 8080
  host: "0.0.0.0"

database:
  host: "localhost"
  port: 5432
  name: "apollo"
  user: "postgres"
  password: "postgres"

redis:
  host: "localhost"
  port: 6379
  password: ""

security:
  jwt_secret: "your-secret-key-here"
  token_expiry: "24h"
  max_failed_attempts: 5
  lockout_duration: "15m"

logging:
  level: "info"
  format: "json"
  output: "stdout"

privilege:
  default_timeout: "1h"
  max_timeout: "24h"
  require_approval: true
  auto_revoke: true 