# Base operator configuration
operator:
  id: "operator-1"
  enabled_modules: "mysql,kubernetes"

# Module configurations
modules:
  mysql:
    enabled: true
    config:
      host: "localhost"
      port: 3306
      user: "root"
      password: "your_password_here"
      database: "apollo"
      max_connections: 10
      connection_timeout: 5s
      idle_timeout: 30s

  kubernetes:
    enabled: true
    config: "/app/config/kubeconfig"
    context: ${KUBERNETES_CONTEXT}
    namespace: ${KUBERNETES_NAMESPACE}
    max_roles: 5
    role_prefix: "apollo-"

# API configuration
api:
  endpoint: "http://api:8080"
  retry_attempts: 3
  retry_delay: "5s"

# Logging configuration
logging:
  level: "info"
  format: "json"
  output: "stdout"

# Health check configuration
health:
  interval: ${HEALTH_INTERVAL:-30s}
  timeout: ${HEALTH_TIMEOUT:-3s}
  retries: ${HEALTH_RETRIES:-3} 