# Base operator configuration
operator:
  id: ${OPERATOR_ID}
  enabled_modules: ${ENABLED_MODULES}

# Module configurations
modules:
  mysql:
    enabled: false
    config:
      host: ${MYSQL_HOST}
      port: ${MYSQL_PORT}
      user: ${MYSQL_USER}
      password: ${MYSQL_PASSWORD}
      max_connections: 10
      connection_timeout: 5s
      idle_timeout: 30s

  kubernetes:
    enabled: false
    config:
      kubeconfig: ${KUBERNETES_CONFIG}
      context: ${KUBERNETES_CONTEXT}
      namespace: ${KUBERNETES_NAMESPACE}
      max_roles: 5
      role_prefix: "apollo-"

# API configuration
api:
  endpoint: ${API_ENDPOINT}
  retry_attempts: 3
  retry_delay: 5s

# Logging configuration
logging:
  level: ${LOG_LEVEL:-info}
  format: ${LOG_FORMAT:-json}
  output: ${LOG_OUTPUT:-stdout}

# Health check configuration
health:
  interval: ${HEALTH_INTERVAL:-30s}
  timeout: ${HEALTH_TIMEOUT:-3s}
  retries: ${HEALTH_RETRIES:-3} 