# Base operator configuration
operator_id: ${OPERATOR_ID:-operator-1}
enabled_modules: "mysql"

# Module configurations
modules:
  mysql:
    host: "mysql"
    port: 3306
    user: "root"
    password: "root"
    max_connections: 10
    connection_timeout: "5s"
    idle_timeout: "5m"

# API configuration
api:
  endpoint: "http://api:8080"
  retry_attempts: 3
  retry_delay: "5s"

# Logging configuration
logging:
  level: "info"
  format: "json"
  output: "stdout"

# Health check configuration
health:
  interval: ${HEALTH_INTERVAL:-30s}
  timeout: ${HEALTH_TIMEOUT:-3s}
  retries: ${HEALTH_RETRIES:-3} 